### ISSUE TITLE
Check possibility of reading files made with firmware < 2

### ISSUE THREAD

**Issue by duartej** [duartej/postproc-alibava#24]
Javi assures that it is possible to read out files created with the firmare version lower than 2 using the same logic than implemented right now @andregarciaa will check it.

**Comment by andregarciaa** [comment]
fortythieves does not allow data files taken with ALIBAVA firmware versions lower than 2. If the line 228 in IOAlibavaReader.cxx is commented, those versions are not rejected. Doing this:

![1a](https://user-images.githubusercontent.com/25437592/38419437-c42bd4d6-39a0-11e8-969c-4769184240fe.png)


the result when executing again fortythieves with data taken with 0 firmware version, as RS 2017 for sensor M1-5 at -25C and -30V, is the following, where it can be appreciated that there is a problem with the calibration file (ignore "Not supported data version found (version=0<2). Data is not saved." messages):

![1a](https://user-images.githubusercontent.com/25437592/38419603-63cb5138-39a1-11e8-98d1-bdb31ef846ab.png)

**Comment by duartej** [comment]
@andregarciaa please upload the files you used in your public directory at lxplus (in order to check and reproduce your problem)

**Comment by andregarciaa** [comment]
@duartej the three files can be found at my workspace/public directory.
2017-05-09_M1_5_MBCERN_-30V-25C_calRSON_-90.8uA.cal
2017-05-09_M1_5_MBCERN_-30V-25C_pedRSON_-90.8uA.ped
2017-05-09_M1_5_MBCERN_-30V-25C_RSON_-90.8uA.dat

**Comment by duartej** [comment]
Just checking the processing of the pedestal and calibration files, you can see that nothing is processed:
>$ fortythieves 2017-05-09_M1_5_MBCERN_-30V-25C_pedRSON_-90.8uA.ped -o $HOME/2017-05->09_M1_5_MBCERN_-30V-25C_pedRSON_-90.8uA.root
>IOAlibavaReader.read_data: Reading '2017-05-09_M1_5_MBCERN_-30V->25C_pedRSON_-90.8uA.ped', run number: -1
> Not supported data version found (version=0<2). Data is not saved.
>Processing  0 from run -1
>Processed 0
>fortythieves INFO: Filling monitor plots CHIP[2][000%]
Equivalent thing happen to the calibration. 

So, it could be two things: 
 * Calibration and pedestal files are empty (weird) or
 * Calibration and pedestals are not well interpreted (because of the firmware version).

@andregarciaa  could you check:
1. that calibration and pedestals files actually contain events (ask Esteban or whoever pass you this files)
2. ask Javi about the ability of his software to interpret firmware<2 calibrated and pedestal data

**Comment by duartej** [comment]
The problem is located in the alibava software choice of the time_t variable to store the data (first field of each file), which is *platform dependent*.
