### ISSUE TITLE
Unexpected changes in the the charge distributions for ```open_sesame sensor_analysis```

### ISSUE THREAD

**Issue by duartej** [duartej/postproc-alibava#25]
Between the commit d5c152a and the commit b493d243, an unexpected change in the sensor analysis has been introduced. Using same input files, the charges distributions are different. Probably this is not the only variable affected, but so far is the one that spotted the issue

**Comment by duartej** [comment]
Files created at March,15 (so probably using the b493d24372 commit, are suposse to behave the same than files created later, as the posterior commits are not changing any of the relevant algorithms.

However, commit 9a281743d1f8f09b33c7967a64ef558189ddcb51 is introducing some changes (which are not well understood) in the analysis python wrapper..

**Comment by andregarciaa** [comment]
The change which has been noticed is that the calibrated charge distributions, although having the same shape, are displaced to the right when processing root files from EOS directory, with respect to the root files Andrea obtain by her one.
Maybe, there is a cut which reduces the amount of collected charge which was not implemented when those root files where generated and now it is?

**Comment by duartej** [comment]
A priori, no extra cut has been implemented between the commits mentioned before, @andregarciaa , but I cannot totally discard that.

**Comment by duartej** [comment]
@andregarciaa as explained somewhere, there is no bug in the code. The differences appear because of not comparing exactly the same things: the initial files were created with the ```-i 2``` option (asymmetric cross-talk correction activated, and performing 2 loops), and the second set without that option. Therefore there is no valid comparation between them.
Closing as invalid (no-bug)
